default_platform(:ios)

platform :ios do
  desc "Upload to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true
    )

    build_app(
      project: "ios/App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      xcargs: "CURRENT_PROJECT_VERSION=#{ENV['BUILD_NUMBER']} DEVELOPMENT_TEAM=X23KWFNCJ4",
      export_options: {
        teamID: "X23KWFNCJ4",
        provisioningProfiles: {
          "com.lastlightpovstudio.mindstep" => "Mindstep Appstore"
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
