default_platform(:ios)

platform :ios do
  desc "Upload to App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true
    )

    build_app(
      project: "ios/App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      xcargs: "DEVELOPMENT_TEAM=X23KWFNCJ4 CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='Mindstep Appstore'",
      export_options: {
        teamID: "X23KWFNCJ4",
        provisioningProfiles: {
          "com.lastlightpovstudio.mindstep" => "Mindstep Appstore"
        }
      }
    )

    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      run_precheck_before_submit: false
    )
  end
end
